### ISSUE TITLE
source code not updated?

### ISSUE THREAD

**Issue by efferre79** [tango-controls/atk-panel#3]
The atkpanel shipped with tango 9.2.5a source code has version 5.5 while here I find version 5.4

**Comment by faranguiss-poncet** [comment]
A new version of ATKPanel jarfile is available for download in https://bintray.com/tango-controls/maven/ATKPanel.
Take care that with this new version you need JRE 1.8 or higher.
If the future Tango Source code package does not include the latest version of AtkPanel (5.7) please open a Tango ticket because it is not an issue for atkpanel project.

**Comment by efferre79** [comment]
Sorry, probably I didn't explain myself properly. 

The latest source archives, at the time I opened this issue (atk-panel-ATKPanel-5.5.tar.gz and atk-panel-ATKPanel-5.6.tar.gz), contain revision 5.4 as stated in MainPanel.java while the tango 9.2.5a sources are shipping binary with atk-panel revision 5.5. I was only wondering where to find the associated source code :-) 

I have also seen the upload of latest version 5.7. Thanks!
